// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"Go-000/Week04/service/logic"
	"Go-000/Week04/service/model"
)

// Injectors from wire.go:

func InitializeServer() (*Server, func(), error) {
	db, cleanup, err := model.NewDB()
	if err != nil {
		return nil, nil, err
	}
	usr := model.NewUser(db)
	serviceService := logic.NewService(usr)
	server := NewServer(serviceService)
	return server, func() {
		cleanup()
	}, nil
}